FROM node:18.14-alpine

RUN npm i -g @nestjs/cli
WORKDIR /node_app
COPY . .
RUN rm -rf node_modules/
RUN rm -rf dist/
RUN npm pkg delete scripts.prepare
RUN npm install --omit=dev
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start:prod"]