version: '3.9'

services:
  nodejs:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - network
    container_name: facilite-node
    volumes:
      - .:/node_app/app
    command: /bin/sh -c "chmod +x entrypoint.sh && /node_app/app/entrypoint.sh"
    env_file:
      - .env

  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    container_name: facilite-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
    depends_on:
      - nodejs

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      network:
        aliases:
          - mysql
    container_name: facilite-mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  adminer:
    image: adminer
    restart: always
    container_name: facilite-adminer
    ports:
      - 8080:8080
    networks:
      - network

networks:
  network:
    driver: bridge
